<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="6843" started-at="2018-08-28T01:06:13Z" finished-at="2018-08-28T01:06:19Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="6843" started-at="2018-08-28T01:06:13Z" finished-at="2018-08-28T01:06:19Z">
      <class name="Test.CalculadoraTest">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:Test.CalculadoraTest@464bee09]" name="beforeMethod" is-config="true" duration-ms="5688" started-at="2018-08-28T01:06:13Z" finished-at="2018-08-28T01:06:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="SomadoismaisdoisTeste()[pri:0, instance:Test.CalculadoraTest@464bee09]" name="SomadoismaisdoisTeste" duration-ms="201" started-at="2018-08-28T01:06:18Z" finished-at="2018-08-28T01:06:19Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [3] but found [2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [3] but found [2]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at Test.CalculadoraTest.SomadoismaisdoisTeste(CalculadoraTest.java:39)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SomadoismaisdoisTeste -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:Test.CalculadoraTest@464bee09]" name="afterMethod" is-config="true" duration-ms="936" started-at="2018-08-28T01:06:19Z" finished-at="2018-08-28T01:06:19Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=SomadoismaisdoisTeste status=FAILURE method=CalculadoraTest.SomadoismaisdoisTeste()[pri:0, instance:Test.CalculadoraTest@464bee09] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- Test.CalculadoraTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
